nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ["*"]
        allow_headers: ["Content-Type", "Authorization", "Accept"]
        allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        max_age: 3600
    paths:
        "^/api/": ~
